mission_van_heist_capture_1_en <- "~h~The Securicar has been captured by the %s.";
mission_van_heist_return_cops_en <- "~h~The Securicar was returned by the Cops.";
mission_van_heist_return_gang_en <- "~r~Bomb timer set. Get away from the car!";
mission_gta_bring_car_home_en <- "~h~Bring the car ~b~home~h~.";
mission_gta_delivered_car_en <- "~h~Your gang delivered a rival gang car.";
mission_gta_steal_message_en <- "~h~Steal a ~y~car ~h~from a rival gangleader!";

keybind_lights_auto_en <- "Lights has been set to automatic.";
bonus_kills_en <- "%s received a bonus of %i$ for %i kills!";
ammunation_rival_en <- "You cannot buy weapons from rival weapon dealers.";
chilling_zone_enter_en <- "Welcome to chilling zone! You are now protected. No fight between man an' man.";
chilling_zone_exit_en <- "Removing protection. See you again!";

command_absent_id_en <- "Error: Absent ID.";
command_help_message_1_en <- "Help:";
command_help_message_2_en <- "Type '/help commands' for information over commands.";
command_help_message_3_en <- "Type '/help bank' for informations about bank system.";
command_help_message_4_en <- "Type '/help dealer' for information about dealer.";
command_help_message_5_en <- "Type '/help manhunt' for informations about manhunt.";
command_help_message_6_en <- "Nick-Server allows you to register your nick, preventing others from using it.";
command_help_commands_message_1_en <- "Help-commands:";
command_help_commands_message_2_en <- "Type '/logout' to log out.";
command_help_commands_message_3_en <- "Type '/login <password>' to log in.";
command_help_commands_message_4_en <- "Type '/register <password>' Register command to register a nick.";
command_help_commands_message_5_en <- "!stats, !loc, !hp, !car, !money, !deposit, !withdraw, !manhunt, !achievements, !buy, !mycar, !gps, !give, !cmd";
command_help_bank_message_1_en <- "Help-Bank:";
command_help_bank_message_2_en <- "You can use a Bank to store your money.";
command_help_bank_message_3_en <- "The money stored in the bank are safe and can't be lost (eg. after dying).";
command_help_bank_message_4_en <- "To use Bank, go to your ammunation and try commands listed below.";
command_help_bank_message_5_en <- "Commands: !deposit <amnout/all>, !withdraw <amnout/all>, !transfermoney <player> <amnout>";
command_help_dealer_message_1_en <- "Help-Car Dealer:";
command_help_dealer_message_2_en <- "You can own a vehicle at Car Dealer.";
command_help_dealer_message_3_en <- "Navigate with '!gps' to the Dealer and enter the garage with a vehicle.";
command_help_dealer_message_4_en <- "Now you can '!buy' the car. Be sure that you have enough money in your pocket!";
command_help_manhunt_message_1_en <- "Help-Manhunt:";
command_help_manhunt_message_2_en <- "Become a hunted player for the 'first blood' kill.";
command_help_manhunt_message_3_en <- "Level up by killing and earn a bonus of $150*Wanted level.";
command_help_manhunt_message_4_en <- "You'll lose your hunt level after leaving the server or being killed.";
command_commands_message_en <- "Available commands: !stats, !loc, !hp, !car, !money, !deposit, !withdraw, !manhunt, !achievements, !buy, !mycar, !gps, !cmd";
command_achievement_en <- "Achievements:\n+100000$ for completing 100 missions of any type.\n+250000$ for completing 250 missions of any type.\n+5000$ for reaching 100 kills.\n+100000$ for reaching 250 kills.\n+200000$ for reaching 500 kills.";
command_register_en <- "Type '/register <password>' Register command to register a nick.";
command_login_en <- "Type '/login <password>'";
command_password_too_long_en <- "Error: Password too long";
command_useregcode_message_1_en <- "You must be registered/logged in to use the registration code.";
command_useregcode_message_2_en <- "Type '/useregcode <code>'";
command_useregcode_message_3_en <- "Incorrect code lenght."
command_server_time_en <- "Server time: %i:%i";
command_money_en <- "Cash: %i, Bank: %i$";
command_deposit_message_1_en <- "Type '!%s <amnout/all>' command to deposit money.";
command_deposit_message_2_en <- "You must be at ammunation to use Bank system.";
command_deposit_message_3_en <- "Error: You have no money to deposit.";
command_deposit_message_4_en <- "Is it a joke? :)";
command_deposit_message_5_en <- "Error: You can't deposit more than you have.";
command_deposit_message_6_en <- "Depositing %i$. Bank status: %i$.";
command_withdraw_message_1_en <- "Type '!%s <amnout/all>' command to withdraw money.";
command_withdraw_message_2_en <- "You must be at ammunation to use Bank system.";
command_withdraw_message_3_en <- "Error: You have no money to witchdraw.";
command_withdraw_message_4_en <- "Is it a joke? :)";
command_withdraw_message_5_en <- "Error: You can't witchdraw more than you have.";
command_withdraw_message_6_en <- "Witchdrawing %i$. Bank status: %i$.";
command_transfer_message_1_en <- "Type '!%s <player> <amnout>' command to transfer bank money.";
command_transfer_message_2_en <- "You must be at ammunation to use Bank system.";
command_transfer_message_3_en <- "Error: You don't have that much money in the bank.";
command_transfer_message_4_en <- "Are you joking? :)";
command_transfer_message_5_en <- "Error: Cannot find player.";
command_transfer_message_6_en <- "Error: missing money amnout.";
command_transfer_message_7_en <- "You've got a registration reward, so you must have at least %i$ left on your account.";
command_transfer_message_8_en <- "%s transfers you %i$ to the bank.";
command_transfer_message_9_en <- "Sent %i$ to %s to the bank.";
command_sendcash_message_1_en <- "Type '!%s <player> <amnout>' command to give cash.";
command_sendcash_message_2_en <- "You must be close to the player.";
command_sendcash_message_3_en <- "Error: You don't have that much cash.";
command_sendcash_message_4_en <- "Are you joking? :)";
command_sendcash_message_5_en <- "Error: Cannot find player.";
command_sendcash_message_6_en <- "Error: missing cash amnout.";
command_sendcash_message_7_en <- "You've got a registration reward, so you must have at least %i$ left on your account.";
command_sendcash_message_8_en <- "%s gives you %i$ cash.";
command_sendcash_message_9_en <- "Gave %i$ to %s.";
command_gpslist_en <- "GPS list: %s";
command_gps_message_1_en <- "GPS commands: !gpslist, !gps <id>, !gps off";
command_gps_message_2_en <- "GPS has been turned off.";
command_gps_message_3_en <- "GPS haven't been set.";
command_gps_message_4_en <- "GPS has been set to %s.";
command_car_buy_1_en <- "You must be at Car Dealer to buy vehicle. Try '!gps'.";
command_mycar_message_en <- "Car commands (only for vehicle owners): !getcar";
command_getcar_message_1_en <- "Type: '!getcar <id>'";
command_getcar_message_1_en <- "Car ID must be numeric.";
command_getcar_message_1_en <- "You must be spawned to use this command.";
command_getcar_message_1_en <- "Cannot teleport vehicles while mission is running.";
command_stats_message_1_en <- "%s Game Kills: %i Deaths: %i Overall Kills: %i Deaths: %i Ratio: %i \nMissions: Manhunt: %i Van Heist: %i GTA: %i Speed: %i";
command_loc_message_1_en <- "%s is in '%s'.";
command_hp_message_1_en <- "%s health: %i%% [%s].";
command_car_message_1_en <- "%s is currently on foot. Health: %i%% [%s].";
command_car_message_2_en <- "%s is currently driving a %s. Vehicle Health: %i%% [%s].\nPlayer Health: %i%% [%s].";
command_manhunt_message_1_en <- "Server is hunting for %s (Level: %i).";
command_manhunt_message_2_en <- "There is no hunting at this moment.";

message_killed_himself_en <- "%s killed himself.";
message_kill_en <- "%s killed %s (%s).";
message_join_player_en <- "Connected to GTA3:MTA server.";
message_happy_hours_en <- "Happy hours bonus (x%i) is active!";
message_nickserver_enabled_en <- "This server has Nick-Server enabled. Register your nickname today!";
message_join_more_informations_en <- "For more information type '/help'.";
message_join_registered_en <- "This account is registered. Use '/login <password>' command.";
message_join_autologin_en <- "'%s' autologged in as a member.";

print( "Loaded english language." );